//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chain
    {
        public Chain()
        {
            this.RicToChains = new HashSet<RicToChain>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public Nullable<long> id_Feed { get; set; }
        public Nullable<System.DateTime> Expanded { get; set; }
        public string Params { get; set; }
    
        public virtual Feed Feed { get; set; }
        public virtual ICollection<RicToChain> RicToChains { get; set; }
    }
}
