//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Borrowers = new HashSet<Borrower>();
            this.Issuers = new HashSet<Issuer>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
    	public Country ToPocoSimple() {
    	    return new Country {
    			id = this.id,
    			Name = this.Name,
    		};
    	}
    		
        public virtual ICollection<Borrower> Borrowers { get; set; }
        public virtual ICollection<Issuer> Issuers { get; set; }
    }
}
