//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainEntities : DbContext
    {
        public MainEntities()
            : base("name=MainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RawBond> RawBonds { get; set; }
        public DbSet<RawFrnData> RawFrnData { get; set; }
        public DbSet<RawRating> RawRatings { get; set; }
        public DbSet<RefBorrower> RefBorrowers { get; set; }
        public DbSet<RefChain> RefChains { get; set; }
        public DbSet<RefCountry> RefCountries { get; set; }
        public DbSet<RefCurrency> RefCurrencies { get; set; }
        public DbSet<RefIndustry> RefIndustries { get; set; }
        public DbSet<RefInstrument> RefInstruments { get; set; }
        public DbSet<RefIsin> RefIsins { get; set; }
        public DbSet<RefIssuer> RefIssuers { get; set; }
        public DbSet<RefRating> RefRatings { get; set; }
        public DbSet<RefRatingAgency> RefRatingAgencies { get; set; }
        public DbSet<RefRic> RefRics { get; set; }
        public DbSet<RefRicToChain> RefRicToChains { get; set; }
        public DbSet<RefSeniority> RefSeniorities { get; set; }
        public DbSet<RefSubIndustry> RefSubIndustries { get; set; }
        public DbSet<RefTicker> RefTickers { get; set; }
        public DbSet<InstrumentCustomBond> InstrumentCustomBonds { get; set; }
        public DbSet<InstrumentBond> InstrumentBonds { get; set; }
        public DbSet<RefRatingToBond> RefRatingToBonds { get; set; }
    }
}
