//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class Description //: IObjectWithState
    {
        public Description()
        {
            this.Instruments = new HashSet<Instrument>();
        }
    
        public long id { get; set; }
        public Nullable<long> id_Issuer { get; set; }
        public Nullable<long> id_Borrower { get; set; }
        public string RateStructure { get; set; }
        public Nullable<long> IssueSize { get; set; }
        public string Series { get; set; }
        public Nullable<long> id_Isin { get; set; }
        public Nullable<long> id_Ric { get; set; }
        public Nullable<long> id_Ticker { get; set; }
        public Nullable<long> id_SubIndustry { get; set; }
        public Nullable<long> id_Specimen { get; set; }
        public Nullable<System.DateTime> Issue { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
        public Nullable<long> id_Seniority { get; set; }
        public Nullable<System.DateTime> NextCoupon { get; set; }
    	public Description ToPocoSimple() {
    	    return new Description {
    			id = this.id,
    			id_Issuer = this.id_Issuer,
    			id_Borrower = this.id_Borrower,
    			RateStructure = this.RateStructure,
    			IssueSize = this.IssueSize,
    			Series = this.Series,
    			id_Isin = this.id_Isin,
    			id_Ric = this.id_Ric,
    			id_Ticker = this.id_Ticker,
    			id_SubIndustry = this.id_SubIndustry,
    			id_Specimen = this.id_Specimen,
    			Issue = this.Issue,
    			Maturity = this.Maturity,
    			id_Seniority = this.id_Seniority,
    			NextCoupon = this.NextCoupon,
    		};
    	}
    
    	//public State State {get;set;}
    		
        public virtual LegalEntity Issuer { get; set; }
        public virtual Specimen Specimen { get; set; }
        public virtual SubIndustry SubIndustry { get; set; }
        public virtual Ticker Ticker { get; set; }
        public virtual Ric Ric { get; set; }
        public virtual Isin Isin { get; set; }
        public virtual LegalEntity Borrower { get; set; }
        public virtual Seniority Seniority { get; set; }
        public virtual ICollection<Instrument> Instruments { get; set; }
    }
}
