//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldVsGroup
    {
        public long id_FieldGroup { get; set; }
        public string Name { get; set; }
        public bool IsDefault { get; set; }
        public string Bid { get; set; }
        public string Ask { get; set; }
        public string Last { get; set; }
        public string Close { get; set; }
        public string VWAP { get; set; }
        public string Volume { get; set; }
    	public FieldVsGroup ToPocoSimple() {
    	    return new FieldVsGroup {
    			id_FieldGroup = this.id_FieldGroup,
    			Name = this.Name,
    			IsDefault = this.IsDefault,
    			Bid = this.Bid,
    			Ask = this.Ask,
    			Last = this.Last,
    			Close = this.Close,
    			VWAP = this.VWAP,
    			Volume = this.Volume,
    		};
    	}
    		}
}
