//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldDefinition
    {
        public FieldDefinition()
        {
            this.Fields = new HashSet<Field>();
            this.FieldGroups = new HashSet<FieldGroup>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
    	public FieldDefinition ToPocoSimple() {
    	    return new FieldDefinition {
    			id = this.id,
    			Name = this.Name,
    		};
    	}
    		
        public virtual ICollection<Field> Fields { get; set; }
        public virtual ICollection<FieldGroup> FieldGroups { get; set; }
    }
}
