//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class Field //: IObjectWithState
    {
        public long id { get; set; }
        public string SystemName { get; set; }
        public long id_FieldGroup { get; set; }
        public long id_FieldDef { get; set; }
    	public Field ToPocoSimple() {
    	    return new Field {
    			id = this.id,
    			SystemName = this.SystemName,
    			id_FieldGroup = this.id_FieldGroup,
    			id_FieldDef = this.id_FieldDef,
    		};
    	}
    
    	//public State State {get;set;}
    		
        public virtual FieldDefinition FieldDefinition { get; set; }
        public virtual FieldGroup FieldGroup { get; set; }
    }
}
