//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldVsGroup
    {
        public long id_FieldGroup { get; set; }
        public long id_Field { get; set; }
        public long id_FieldDefinition { get; set; }
        public long id_DefaultFieldDefinition { get; set; }
        public bool DefaultGroup { get; set; }
        public string FieldGroupName { get; set; }
        public string SystemName { get; set; }
        public string InternalName { get; set; }
    	public FieldVsGroup ToPocoSimple() {
    	    return new FieldVsGroup {
    			id_FieldGroup = this.id_FieldGroup,
    			id_Field = this.id_Field,
    			id_FieldDefinition = this.id_FieldDefinition,
    			id_DefaultFieldDefinition = this.id_DefaultFieldDefinition,
    			DefaultGroup = this.DefaultGroup,
    			FieldGroupName = this.FieldGroupName,
    			SystemName = this.SystemName,
    			InternalName = this.InternalName,
    		};
    	}
    		}
}
