//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class Index //: IObjectWithState
    {
        public Index()
        {
            this.Legs = new HashSet<Leg>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public Nullable<long> id_Ric { get; set; }
    	public Index ToPocoSimple() {
    	    return new Index {
    			id = this.id,
    			Name = this.Name,
    			id_Ric = this.id_Ric,
    		};
    	}
    
    	//public State State {get;set;}
    		
        public virtual Ric Ric { get; set; }
        public virtual ICollection<Leg> Legs { get; set; }
    }
}
