//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Index
    {
        public Index()
        {
            this.InstrumentFrns = new HashSet<InstrumentFrn>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public string Ric { get; set; }
        public Nullable<long> id_FieldGroup { get; set; }
    	public Index ToPocoSimple() {
    	    return new Index {
    			id = this.id,
    			Name = this.Name,
    			Ric = this.Ric,
    			id_FieldGroup = this.id_FieldGroup,
    		};
    	}
    		
        public virtual ICollection<InstrumentFrn> InstrumentFrns { get; set; }
        public virtual FieldGroup FieldGroup { get; set; }
    }
}
