//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class Industry //: IObjectWithState
    {
        public Industry()
        {
            this.SubIndustries = new HashSet<SubIndustry>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
    	public Industry ToPocoSimple() {
    	    return new Industry {
    			id = this.id,
    			Name = this.Name,
    		};
    	}
    
    	//public State State {get;set;}
    		
        public virtual ICollection<SubIndustry> SubIndustries { get; set; }
    }
}
