//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentCustomBond
    {
        public long id { get; set; }
        public string Name { get; set; }
        public string BondStructure { get; set; }
        public string RateStructure { get; set; }
        public Nullable<long> id_Currency { get; set; }
        public Nullable<System.DateTime> Issue { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
    	public InstrumentCustomBond ToPocoSimple() {
    	    return new InstrumentCustomBond {
    			id = this.id,
    			Name = this.Name,
    			BondStructure = this.BondStructure,
    			RateStructure = this.RateStructure,
    			id_Currency = this.id_Currency,
    			Issue = this.Issue,
    			Maturity = this.Maturity,
    		};
    	}
    		
        public virtual Currency Currency { get; set; }
    }
}
