//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstrumentDescriptionView
    {
        public long id_Instrument { get; set; }
        public string InstrumentName { get; set; }
        public string InstrumentTypeName { get; set; }
        public long id_InstrumentType { get; set; }
        public Nullable<long> IssueSize { get; set; }
        public string Series { get; set; }
        public Nullable<System.DateTime> Issue { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
        public Nullable<System.DateTime> NextCoupon { get; set; }
        public string TickerName { get; set; }
        public string SubIndustryName { get; set; }
        public string IndustryName { get; set; }
        public string SpecimenName { get; set; }
        public string SeniorityName { get; set; }
        public string RicName { get; set; }
        public string IsinName { get; set; }
        public string BorrowerName { get; set; }
        public string BorrowerCountryName { get; set; }
        public string IssuerName { get; set; }
        public string IssuerCountryName { get; set; }
        public string InstrumentRating { get; set; }
        public Nullable<System.DateTime> InstrumentRatingDate { get; set; }
        public string InstrumentRatingAgency { get; set; }
        public string IssuerRating { get; set; }
        public Nullable<System.DateTime> IssuerRatingDate { get; set; }
        public string IssuerRatingAgency { get; set; }
    	public InstrumentDescriptionView ToPocoSimple() {
    	    return new InstrumentDescriptionView {
    			id_Instrument = this.id_Instrument,
    			InstrumentName = this.InstrumentName,
    			InstrumentTypeName = this.InstrumentTypeName,
    			id_InstrumentType = this.id_InstrumentType,
    			IssueSize = this.IssueSize,
    			Series = this.Series,
    			Issue = this.Issue,
    			Maturity = this.Maturity,
    			NextCoupon = this.NextCoupon,
    			TickerName = this.TickerName,
    			SubIndustryName = this.SubIndustryName,
    			IndustryName = this.IndustryName,
    			SpecimenName = this.SpecimenName,
    			SeniorityName = this.SeniorityName,
    			RicName = this.RicName,
    			IsinName = this.IsinName,
    			BorrowerName = this.BorrowerName,
    			BorrowerCountryName = this.BorrowerCountryName,
    			IssuerName = this.IssuerName,
    			IssuerCountryName = this.IssuerCountryName,
    			InstrumentRating = this.InstrumentRating,
    			InstrumentRatingDate = this.InstrumentRatingDate,
    			InstrumentRatingAgency = this.InstrumentRatingAgency,
    			IssuerRating = this.IssuerRating,
    			IssuerRatingDate = this.IssuerRatingDate,
    			IssuerRatingAgency = this.IssuerRatingAgency,
    		};
    	}
    		}
}
