//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instrument
    {
        public Instrument()
        {
            this.Legs = new HashSet<Leg>();
            this.RatingToInstruments = new HashSet<RatingToInstrument>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public Nullable<long> id_InstrumentType { get; set; }
        public Nullable<long> id_Description { get; set; }
    	public Instrument ToPocoSimple() {
    	    return new Instrument {
    			id = this.id,
    			Name = this.Name,
    			id_InstrumentType = this.id_InstrumentType,
    			id_Description = this.id_Description,
    		};
    	}
    		
        public virtual Description Description { get; set; }
        public virtual InstrumentType InstrumentType { get; set; }
        public virtual ICollection<Leg> Legs { get; set; }
        public virtual ICollection<RatingToInstrument> RatingToInstruments { get; set; }
    }
}
