//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class InstrumentRicView //: IObjectWithState
    {
        public long id_Ric { get; set; }
        public long id_Instrument { get; set; }
        public long id_Description { get; set; }
        public string Name { get; set; }
    	public InstrumentRicView ToPocoSimple() {
    	    return new InstrumentRicView {
    			id_Ric = this.id_Ric,
    			id_Instrument = this.id_Instrument,
    			id_Description = this.id_Description,
    			Name = this.Name,
    		};
    	}
    
    	//public State State {get;set;}
    		}
}
