//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class Isin //: IObjectWithState
    {
        public Isin()
        {
            this.Rics = new HashSet<Ric>();
            this.Descriptions = new HashSet<Description>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public Nullable<long> id_Feed { get; set; }
    	public Isin ToPocoSimple() {
    	    return new Isin {
    			id = this.id,
    			Name = this.Name,
    			id_Feed = this.id_Feed,
    		};
    	}
    
    	//public State State {get;set;}
    		
        public virtual Feed Feed { get; set; }
        public virtual ICollection<Ric> Rics { get; set; }
        public virtual ICollection<Description> Descriptions { get; set; }
    }
}
