//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issuer
    {
        public Issuer()
        {
            this.InstrumentBonds = new HashSet<InstrumentBond>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public long id_Country { get; set; }
    	public Issuer ToPocoSimple() {
    	    return new Issuer {
    			id = this.id,
    			Name = this.Name,
    			id_Country = this.id_Country,
    		};
    	}
    		
        public virtual Country Country { get; set; }
        public virtual ICollection<InstrumentBond> InstrumentBonds { get; set; }
    }
}
