//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leg
    {
        public long id { get; set; }
        public string Structure { get; set; }
        public Nullable<long> id_Instrument { get; set; }
        public Nullable<long> id_LegType { get; set; }
        public Nullable<long> id_Currency { get; set; }
        public Nullable<double> FixedRate { get; set; }
        public Nullable<long> id_Index { get; set; }
        public Nullable<double> Cap { get; set; }
        public Nullable<double> Floor { get; set; }
        public Nullable<double> Margin { get; set; }
    	public Leg ToPocoSimple() {
    	    return new Leg {
    			id = this.id,
    			Structure = this.Structure,
    			id_Instrument = this.id_Instrument,
    			id_LegType = this.id_LegType,
    			id_Currency = this.id_Currency,
    			FixedRate = this.FixedRate,
    			id_Index = this.id_Index,
    			Cap = this.Cap,
    			Floor = this.Floor,
    			Margin = this.Margin,
    		};
    	}
    		
        public virtual LegType LegType { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Index Index { get; set; }
        public virtual Instrument Instrument { get; set; }
    }
}
