//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class LegalEntity //: IObjectWithState
    {
        public LegalEntity()
        {
            this.RatingToLegalEntities = new HashSet<RatingToLegalEntity>();
            this.IssuerDescriptions = new HashSet<Description>();
            this.BorrowerDescriptions = new HashSet<Description>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public long id_Country { get; set; }
    	public LegalEntity ToPocoSimple() {
    	    return new LegalEntity {
    			id = this.id,
    			Name = this.Name,
    			id_Country = this.id_Country,
    		};
    	}
    
    	//public State State {get;set;}
    		
        public virtual Country Country { get; set; }
        public virtual ICollection<RatingToLegalEntity> RatingToLegalEntities { get; set; }
        public virtual ICollection<Description> IssuerDescriptions { get; set; }
        public virtual ICollection<Description> BorrowerDescriptions { get; set; }
    }
}
