//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegType
    {
        public LegType()
        {
            this.Legs = new HashSet<Leg>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
    	public LegType ToPocoSimple() {
    	    return new LegType {
    			id = this.id,
    			Name = this.Name,
    		};
    	}
    		
        public virtual ICollection<Leg> Legs { get; set; }
    }
}
