//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class OrdinaryBond //: IObjectWithState
    {
        public long id_Instrument { get; set; }
        public string Name { get; set; }
        public string Series { get; set; }
        public Nullable<long> IssueSize { get; set; }
        public string RateStructure { get; set; }
        public string BondStructure { get; set; }
        public Nullable<long> id_Issuer { get; set; }
        public Nullable<long> id_Borrower { get; set; }
        public long id_Isin { get; set; }
        public long id_Ric { get; set; }
        public string Isin { get; set; }
        public string Ric { get; set; }
        public Nullable<long> id_Ticker { get; set; }
        public Nullable<long> id_SubIndustry { get; set; }
        public Nullable<long> id_Specimen { get; set; }
        public Nullable<long> id_Seniority { get; set; }
        public Nullable<System.DateTime> Issue { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
        public Nullable<System.DateTime> NextCoupon { get; set; }
        public Nullable<double> Coupon { get; set; }
        public Nullable<long> id_Currency { get; set; }
    	public OrdinaryBond ToPocoSimple() {
    	    return new OrdinaryBond {
    			id_Instrument = this.id_Instrument,
    			Name = this.Name,
    			Series = this.Series,
    			IssueSize = this.IssueSize,
    			RateStructure = this.RateStructure,
    			BondStructure = this.BondStructure,
    			id_Issuer = this.id_Issuer,
    			id_Borrower = this.id_Borrower,
    			id_Isin = this.id_Isin,
    			id_Ric = this.id_Ric,
    			Isin = this.Isin,
    			Ric = this.Ric,
    			id_Ticker = this.id_Ticker,
    			id_SubIndustry = this.id_SubIndustry,
    			id_Specimen = this.id_Specimen,
    			id_Seniority = this.id_Seniority,
    			Issue = this.Issue,
    			Maturity = this.Maturity,
    			NextCoupon = this.NextCoupon,
    			Coupon = this.Coupon,
    			id_Currency = this.id_Currency,
    		};
    	}
    
    	//public State State {get;set;}
    		}
}
