//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyToInstrumentType
    {
        public long id { get; set; }
        public Nullable<long> id_InstrumentType { get; set; }
        public Nullable<long> id_Property { get; set; }
    	public PropertyToInstrumentType ToPocoSimple() {
    	    return new PropertyToInstrumentType {
    			id = this.id,
    			id_InstrumentType = this.id_InstrumentType,
    			id_Property = this.id_Property,
    		};
    	}
    		
        public virtual InstrumentType InstrumentType { get; set; }
        public virtual Property Property { get; set; }
    }
}
