//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class Property //: IObjectWithState
    {
        public Property()
        {
            this.PropertyValues = new HashSet<PropertyValue>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Expression { get; set; }
    	public Property ToPocoSimple() {
    	    return new Property {
    			id = this.id,
    			Name = this.Name,
    			Description = this.Description,
    			Expression = this.Expression,
    		};
    	}
    
    	//public State State {get;set;}
    		
        public virtual ICollection<PropertyValue> PropertyValues { get; set; }
    }
}
