//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyValue
    {
        public long id { get; set; }
        public Nullable<long> id_Property { get; set; }
        public Nullable<long> id_Instrument { get; set; }
        public string StringValue { get; set; }
        public Nullable<long> IntValue { get; set; }
        public Nullable<double> FloatValue { get; set; }
    	public PropertyValue ToPocoSimple() {
    	    return new PropertyValue {
    			id = this.id,
    			id_Property = this.id_Property,
    			id_Instrument = this.id_Instrument,
    			StringValue = this.StringValue,
    			IntValue = this.IntValue,
    			FloatValue = this.FloatValue,
    		};
    	}
    		
        public virtual Instrument Instrument { get; set; }
        public virtual Property Property { get; set; }
    }
}
