//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public Property()
        {
            this.PropertyToInstrumentTypes = new HashSet<PropertyToInstrumentType>();
            this.PropertyValues = new HashSet<PropertyValue>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Expression { get; set; }
        public Nullable<long> id_PropertyType { get; set; }
    	public Property ToPocoSimple() {
    	    return new Property {
    			id = this.id,
    			Name = this.Name,
    			Description = this.Description,
    			Expression = this.Expression,
    			id_PropertyType = this.id_PropertyType,
    		};
    	}
    		
        public virtual PropertyType PropertyType { get; set; }
        public virtual ICollection<PropertyToInstrumentType> PropertyToInstrumentTypes { get; set; }
        public virtual ICollection<PropertyValue> PropertyValues { get; set; }
    }
}
