//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingAgency
    {
        public long id { get; set; }
        public string Name { get; set; }
    	public RatingAgency ToPocoSimple() {
    	    return new RatingAgency {
    			id = this.id,
    			Name = this.Name,
    		};
    	}
    		
        public virtual Rating Rating { get; set; }
    }
}
