//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingToLegalEntity
    {
        public long id { get; set; }
        public long id_Rating { get; set; }
        public Nullable<long> id_LegalEntity { get; set; }
    	public RatingToLegalEntity ToPocoSimple() {
    	    return new RatingToLegalEntity {
    			id = this.id,
    			id_Rating = this.id_Rating,
    			id_LegalEntity = this.id_LegalEntity,
    		};
    	}
    		
        public virtual LegalEntity LegalEntity { get; set; }
        public virtual Rating Rating { get; set; }
    }
}
