//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class Rating //: IObjectWithState
    {
        public Rating()
        {
            this.RatingToInstruments = new HashSet<RatingToInstrument>();
            this.RatingToLegalEntities = new HashSet<RatingToLegalEntity>();
        }
    
        public long id { get; set; }
        public long Value { get; set; }
        public string Name { get; set; }
        public long id_RatingAgency { get; set; }
    	public Rating ToPocoSimple() {
    	    return new Rating {
    			id = this.id,
    			Value = this.Value,
    			Name = this.Name,
    			id_RatingAgency = this.id_RatingAgency,
    		};
    	}
    
    	//public State State {get;set;}
    		
        public virtual RatingAgency RatingAgency { get; set; }
        public virtual ICollection<RatingToInstrument> RatingToInstruments { get; set; }
        public virtual ICollection<RatingToLegalEntity> RatingToLegalEntities { get; set; }
    }
}
