//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingsView
    {
        public long id_Rating { get; set; }
        public long id_RatingAgency { get; set; }
        public long id_RatingAgencyCode { get; set; }
        public long RatingOrder { get; set; }
        public string RatingName { get; set; }
        public string AgencyName { get; set; }
        public string AgencyCode { get; set; }
    	public RatingsView ToPocoSimple() {
    	    return new RatingsView {
    			id_Rating = this.id_Rating,
    			id_RatingAgency = this.id_RatingAgency,
    			id_RatingAgencyCode = this.id_RatingAgencyCode,
    			RatingOrder = this.RatingOrder,
    			RatingName = this.RatingName,
    			AgencyName = this.AgencyName,
    			AgencyCode = this.AgencyCode,
    		};
    	}
    		}
}
