//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingToInstrument
    {
        public long id { get; set; }
        public long id_Rating { get; set; }
        public Nullable<long> id_Instrument { get; set; }
    	public RatingToInstrument ToPocoSimple() {
    	    return new RatingToInstrument {
    			id = this.id,
    			id_Rating = this.id_Rating,
    			id_Instrument = this.id_Instrument,
    		};
    	}
    		
        public virtual Rating Rating { get; set; }
        public virtual Instrument Instrument { get; set; }
    }
}
