//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class RatingAgencyCode //: IObjectWithState
    {
        public long id { get; set; }
        public string Name { get; set; }
        public long id_RatingAgency { get; set; }
    	public RatingAgencyCode ToPocoSimple() {
    	    return new RatingAgencyCode {
    			id = this.id,
    			Name = this.Name,
    			id_RatingAgency = this.id_RatingAgency,
    		};
    	}
    
    	//public State State {get;set;}
    		
        public virtual RatingAgency RatingAgency { get; set; }
    }
}
