//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class RatingAgency //: IObjectWithState
    {
        public RatingAgency()
        {
            this.Ratings = new HashSet<Rating>();
            this.RatingAgencyCodes = new HashSet<RatingAgencyCode>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    	public RatingAgency ToPocoSimple() {
    	    return new RatingAgency {
    			id = this.id,
    			Name = this.Name,
    			Description = this.Description,
    		};
    	}
    
    	//public State State {get;set;}
    		
        public virtual ICollection<Rating> Ratings { get; set; }
        public virtual ICollection<RatingAgencyCode> RatingAgencyCodes { get; set; }
    }
}
