//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public Rating()
        {
            this.InstrumentBonds = new HashSet<InstrumentBond>();
        }
    
        public long id { get; set; }
        public long Value { get; set; }
        public string Name { get; set; }
        public Nullable<long> id_RatingAgency { get; set; }
    	public Rating ToPocoSimple() {
    	    return new Rating {
    			id = this.id,
    			Value = this.Value,
    			Name = this.Name,
    			id_RatingAgency = this.id_RatingAgency,
    		};
    	}
    		
        public virtual RatingAgency RatingAgency { get; set; }
        public virtual ICollection<InstrumentBond> InstrumentBonds { get; set; }
    }
}
