//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawBondInfo
    {
        public RawBondInfo()
        {
            this.RawFrnDatas = new HashSet<RawFrnData>();
            this.RawRatings = new HashSet<RawRating>();
        }
    
        public long id { get; set; }
        public string BondStructure { get; set; }
        public string RateStructure { get; set; }
        public Nullable<long> IssueSize { get; set; }
        public string IssuerName { get; set; }
        public string BorrowerName { get; set; }
        public Nullable<double> Coupon { get; set; }
        public Nullable<System.DateTime> Issue { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
        public string Currency { get; set; }
        public string ShortName { get; set; }
        public bool IsCallable { get; set; }
        public bool IsPutable { get; set; }
        public bool IsFloater { get; set; }
        public bool IsConvertible { get; set; }
        public bool IsStraight { get; set; }
        public string Ticker { get; set; }
        public string Series { get; set; }
        public string BorrowerCountry { get; set; }
        public string IssuerCountry { get; set; }
        public string Isin { get; set; }
        public string ParentTicker { get; set; }
        public string Seniority { get; set; }
        public string Industry { get; set; }
        public string SubIndustry { get; set; }
        public string Instrument { get; set; }
        public string Ric { get; set; }
    	public RawBondInfo ToPocoSimple() {
    	    return new RawBondInfo {
    			id = this.id,
    			BondStructure = this.BondStructure,
    			RateStructure = this.RateStructure,
    			IssueSize = this.IssueSize,
    			IssuerName = this.IssuerName,
    			BorrowerName = this.BorrowerName,
    			Coupon = this.Coupon,
    			Issue = this.Issue,
    			Maturity = this.Maturity,
    			Currency = this.Currency,
    			ShortName = this.ShortName,
    			IsCallable = this.IsCallable,
    			IsPutable = this.IsPutable,
    			IsFloater = this.IsFloater,
    			IsConvertible = this.IsConvertible,
    			IsStraight = this.IsStraight,
    			Ticker = this.Ticker,
    			Series = this.Series,
    			BorrowerCountry = this.BorrowerCountry,
    			IssuerCountry = this.IssuerCountry,
    			Isin = this.Isin,
    			ParentTicker = this.ParentTicker,
    			Seniority = this.Seniority,
    			Industry = this.Industry,
    			SubIndustry = this.SubIndustry,
    			Instrument = this.Instrument,
    			Ric = this.Ric,
    		};
    	}
    		
        public virtual ICollection<RawFrnData> RawFrnDatas { get; set; }
        public virtual ICollection<RawRating> RawRatings { get; set; }
    }
}
