//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawBond
    {
        public RawBond()
        {
            this.RawFrnDatas = new HashSet<RawFrnData>();
            this.RawRatings = new HashSet<RawRating>();
        }
    
        public long id { get; set; }
        public string BondStructure { get; set; }
        public string RateStructure { get; set; }
        public Nullable<long> IssueSize { get; set; }
        public string IssuerName { get; set; }
        public string BorrowerName { get; set; }
        public Nullable<double> Coupon { get; set; }
        public Nullable<System.DateTime> Issue { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
        public string Currency { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> IsCallable { get; set; }
        public Nullable<bool> IsPutable { get; set; }
        public Nullable<bool> IsFloater { get; set; }
        public Nullable<bool> IsConvertible { get; set; }
        public Nullable<bool> IsStraight { get; set; }
        public string Ticker { get; set; }
        public string Series { get; set; }
        public string BorrowerCountry { get; set; }
        public string IssuerCountry { get; set; }
        public string Isin { get; set; }
        public string ParentTicker { get; set; }
        public string Seniority { get; set; }
        public string Industry { get; set; }
        public string SubIndustry { get; set; }
        public string Instrument { get; set; }
    
        public virtual ICollection<RawFrnData> RawFrnDatas { get; set; }
        public virtual ICollection<RawRating> RawRatings { get; set; }
    }
}
