//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawFrnData
    {
        public long id { get; set; }
        public Nullable<double> Cap { get; set; }
        public Nullable<double> Floor { get; set; }
        public Nullable<double> Margin { get; set; }
        public string Index { get; set; }
        public Nullable<long> id_RawBond { get; set; }
        public string Frequency { get; set; }
    
        public virtual RawBond RawBondInfo { get; set; }
    }
}
