//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawFrnData
    {
        public long id { get; set; }
        public Nullable<double> Cap { get; set; }
        public Nullable<double> Floor { get; set; }
        public Nullable<double> Margin { get; set; }
        public string Index { get; set; }
        public Nullable<long> id_RawBond { get; set; }
        public string Frequency { get; set; }
    	public RawFrnData ToPocoSimple() {
    	    return new RawFrnData {
    			id = this.id,
    			Cap = this.Cap,
    			Floor = this.Floor,
    			Margin = this.Margin,
    			Index = this.Index,
    			id_RawBond = this.id_RawBond,
    			Frequency = this.Frequency,
    		};
    	}
    		
        public virtual RawBondInfo RawBondInfo { get; set; }
    }
}
