//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawRating
    {
        public long id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Rating { get; set; }
        public string Source { get; set; }
        public Nullable<bool> Issue { get; set; }
        public Nullable<long> id_RawBond { get; set; }
    	public RawRating ToPocoSimple() {
    	    return new RawRating {
    			id = this.id,
    			Date = this.Date,
    			Rating = this.Rating,
    			Source = this.Source,
    			Issue = this.Issue,
    			id_RawBond = this.id_RawBond,
    		};
    	}
    		
        public virtual RawBondInfo RawBondInfo { get; set; }
    }
}
