//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefCountry
    {
        public RefCountry()
        {
            this.RefBorrowers = new HashSet<RefBorrower>();
            this.RefIssuers = new HashSet<RefIssuer>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<RefBorrower> RefBorrowers { get; set; }
        public virtual ICollection<RefIssuer> RefIssuers { get; set; }
    }
}
