//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefRatingToBond
    {
        public long id { get; set; }
        public Nullable<long> id_Rating { get; set; }
        public Nullable<long> id_Bond { get; set; }
    
        public virtual InstrumentBond InstrumentBond { get; set; }
        public virtual RefRating RefRating { get; set; }
    }
}
