//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefRicToChain
    {
        public long id { get; set; }
        public long Ric_id { get; set; }
        public long Chain_id { get; set; }
    
        public virtual RefChain RefChain { get; set; }
        public virtual RefRic RefRic { get; set; }
    }
}
