//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seniority
    {
        public Seniority()
        {
            this.Descriptions = new HashSet<Description>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
    	public Seniority ToPocoSimple() {
    	    return new Seniority {
    			id = this.id,
    			Name = this.Name,
    		};
    	}
    		
        public virtual ICollection<Description> Descriptions { get; set; }
    }
}
