//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YieldMap.Database
{
    using System;
    using System.Collections.Generic;
    //using YieldMap.Database.Domains;
    public partial class SubIndustry //: IObjectWithState
    {
        public SubIndustry()
        {
            this.Descriptions = new HashSet<Description>();
        }
    
        public long id { get; set; }
        public string Name { get; set; }
        public long id_Industry { get; set; }
    	public SubIndustry ToPocoSimple() {
    	    return new SubIndustry {
    			id = this.id,
    			Name = this.Name,
    			id_Industry = this.id_Industry,
    		};
    	}
    
    	//public State State {get;set;}
    		
        public virtual Industry Industry { get; set; }
        public virtual ICollection<Description> Descriptions { get; set; }
    }
}
